project:
  type: website
  output-dir: docs

website:
  title: "Proyecto Final"
  site-url: "https://dwdmv.github.io/proyecto-final/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



